adobe/aepsdk-analytics-android

code/analytics/build.gradle

license update in gradle script

---

code/analytics/src/main/java/com/adobe/marketing/mobile/analytics/internal/AnalyticsExtension.kt
code/analytics/src/main/java/com/adobe/marketing/mobile/analytics/internal/AnalyticsProperties.kt
code/analytics/src/test/java/com/adobe/marketing/mobile/analytics/function/test/AnalyticsIDTests.kt

Fix cached properties to get latest values from dataStore everytime

---

code/analytics/src/main/java/com/adobe/marketing/mobile/analytics/internal/AnalyticsHitProcessor.kt
code/analytics/src/test/java/com/adobe/marketing/mobile/analytics/internal/AnalyticsHitProcessorTests.kt
code/analytics/src/test/java/com/adobe/marketing/mobile/analytics/internal/MockedHttpConnecting.kt

Fixes for Analytics hit response logic

---

Documentation/api-reference.md
code/analytics/src/main/java/com/adobe/marketing/mobile/analytics/internal/AnalyticsDatabase.kt
code/analytics/src/main/java/com/adobe/marketing/mobile/analytics/internal/AnalyticsExtension.kt
code/analytics/src/main/java/com/adobe/marketing/mobile/analytics/internal/AnalyticsHit.kt
code/analytics/src/main/java/com/adobe/marketing/mobile/analytics/internal/AnalyticsHitProcessor.kt
code/analytics/src/main/java/com/adobe/marketing/mobile/analytics/internal/AnalyticsProperties.kt
code/analytics/src/main/java/com/adobe/marketing/mobile/analytics/internal/AnalyticsRequestSerializer.kt
code/analytics/src/main/java/com/adobe/marketing/mobile/analytics/internal/AnalyticsVersionProvider.kt
code/analytics/src/main/java/com/adobe/marketing/mobile/analytics/internal/ContextDataUtil.java
code/analytics/src/phone/java/com/adobe/marketing/mobile/Analytics.java
code/testapp/src/main/java/com/adobe/analyticstestapp/AnalyticsTrackingReceiver.java

Add class and method documentation

---

Documentation/api-reference.md
code/analytics/src/main/java/com/adobe/marketing/mobile/analytics/internal/AnalyticsDatabase.kt
code/analytics/src/main/java/com/adobe/marketing/mobile/analytics/internal/AnalyticsExtension.kt
code/analytics/src/main/java/com/adobe/marketing/mobile/analytics/internal/AnalyticsHit.kt
code/analytics/src/main/java/com/adobe/marketing/mobile/analytics/internal/AnalyticsHitProcessor.kt
code/analytics/src/main/java/com/adobe/marketing/mobile/analytics/internal/AnalyticsProperties.kt
code/analytics/src/main/java/com/adobe/marketing/mobile/analytics/internal/AnalyticsRequestSerializer.kt
code/analytics/src/main/java/com/adobe/marketing/mobile/analytics/internal/AnalyticsVersionProvider.kt
code/analytics/src/main/java/com/adobe/marketing/mobile/analytics/internal/ContextDataUtil.java
code/analytics/src/phone/java/com/adobe/marketing/mobile/Analytics.java
code/testapp/src/main/java/com/adobe/analyticstestapp/AnalyticsTrackingReceiver.java

dev -> staging for 2.0.0-SNAPSHOT

---

Documentation/api-reference.md

Remove Kotlin syntax in the doc

Remove Kotlin syntax in the doc

---

code/analytics/src/main/java/com/adobe/marketing/mobile/analytics/internal/AnalyticsExtension.kt
code/analytics/src/test/java/com/adobe/marketing/mobile/analytics/function/test/AnalyticsIDTests.kt

Separate the logic for get/set identities and only send a shared state update for set requests.
If the set request contains invalid value type for vid (not a string), ignore the request.

Update handler for IdentityRequests (resolves #43)

---

code/analytics/src/main/java/com/adobe/marketing/mobile/analytics/internal/AnalyticsConstants.kt
code/analytics/src/phone/java/com/adobe/marketing/mobile/Analytics.java
code/analytics/src/test/java/com/adobe/marketing/mobile/analytics/internal/AnalyticsExtensionVersionTest.kt
code/gradle.properties

Update extension version to 2.0.1
Updates core dependency to 2.0.1 that includes latest stability fixes

version 2.0.1

---

code/gradle.properties
code/testapp/src/main/java/com/adobe/analyticstestapp/MainActivity.java
code/testapp/src/main/res/layout/activity_main.xml

Add support for integration testing with Identity extension and custom ids

Update testing support with TestApp

---

code/analytics/src/main/java/com/adobe/marketing/mobile/analytics/internal/AnalyticsConstants.kt
code/analytics/src/phone/java/com/adobe/marketing/mobile/Analytics.java
code/gradle.properties

version 2.0.2

---

code/analytics/src/main/java/com/adobe/marketing/mobile/analytics/internal/AnalyticsConstants.kt
code/analytics/src/main/java/com/adobe/marketing/mobile/analytics/internal/AnalyticsHitProcessor.kt
code/analytics/src/main/java/com/adobe/marketing/mobile/analytics/internal/AnalyticsState.kt
code/analytics/src/phone/java/com/adobe/marketing/mobile/Analytics.java
code/analytics/src/test/java/com/adobe/marketing/mobile/analytics/internal/AnalyticsHitProcessorTests.kt
code/analytics/src/test/java/com/adobe/marketing/mobile/analytics/internal/AnalyticsStateTests.kt
code/gradle.properties

dev-v2.0.2 -> staging

---

code/analytics/src/main/java/com/adobe/marketing/mobile/analytics/internal/AnalyticsConstants.kt
code/analytics/src/test/java/com/adobe/marketing/mobile/analytics/function/test/AnalyticsTrackLifecycleTests.kt
code/analytics/src/test/java/com/adobe/marketing/mobile/analytics/function/test/HitReorderTests.kt

Support system locale in lifecycle hits to analytics

---

code/analytics/build.gradle
code/testapp/build.gradle

Fix Warnings in Gradle files

---

code/analytics/build.gradle.kts
code/analytics/src/main/java/com/adobe/marketing/mobile/analytics/internal/AnalyticsConstants.kt
code/analytics/src/phone/java/com/adobe/marketing/mobile/Analytics.java
code/build.gradle.kts
code/gradle.properties
code/testapp/build.gradle.kts

Update version to 3.0.0-beta.1

Update version to 3.0.0-beta.1

---

code/analytics/src/main/java/com/adobe/marketing/mobile/analytics/internal/AnalyticsConstants.kt
code/analytics/src/phone/java/com/adobe/marketing/mobile/Analytics.java
code/analytics/src/test/java/com/adobe/marketing/mobile/analytics/internal/AnalyticsExtensionVersionTest.kt

Update extension_version back to 3.0.0 
Ignore the version check test for gradle.properties and extension version.

Update extension_version back to 3.0.0 for beta 1 release

---

.circleci/config.yml
Documentation/getting-started.md
code/build.gradle.kts

clean up before the release
- Gettin started docs - Update Bom setup - groovy + kotlin instructions
- Update gradle lib to gp-3.0.0
- Remove sample app reference in the Readme
- Update Ci to run build sample only for staging and main
- Fix the path for store_artifacts

clean up before the release

---

code/testapp/build.gradle.kts

update assurance to staging in the test app, merge down from staging

Update assurance to staging in the test app, merge down from staging

---

.circleci/config.yml
Documentation/getting-started.md
code/build.gradle.kts
code/testapp/build.gradle.kts

3.0.0 release final dev-v3.0.0 -> staging

3.0.0 release final dev-v3.0.0 -> staging

---

README.md

Update development steps in readme

---

code/analytics/build.gradle.kts
code/testapp/build.gradle.kts

Set up dependencies for release

Set up dependencies for release

---

code/analytics/build.gradle.kts
code/testapp/build.gradle.kts

staging-v3-dep-updates -> staging

staging-v3-dep-updates -> staging
